In [1]:
# numpy import
import numpy as np

In [2]:
# word embedding:  dictionary that maps word indexes to weights (numbers)
embedding = {i: np.random.normal(0, .1, 10) for i in range(10001)}

In [3]:
# observe what it is
embedding

{0: array([ 0.0201575 , -0.00849058, -0.00466075, -0.01103659,  0.05213042,
        -0.28017484, -0.03202388,  0.0736791 , -0.09002325, -0.18466544]),
 1: array([-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
        -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561]),
 2: array([-0.11173917, -0.03611451,  0.09825518, -0.23787552,  0.07083221,
         0.01708899, -0.01817694, -0.0409453 , -0.12994312, -0.03496482]),
 3: array([ 0.1608604 ,  0.01325084, -0.09057018, -0.19575602, -0.01248113,
        -0.06494003, -0.12170885, -0.0440194 ,  0.00523634,  0.02661695]),
 4: array([-0.10865877,  0.01773715, -0.02189519,  0.13157712,  0.06519128,
        -0.15469799,  0.14717475, -0.00379139, -0.08324313, -0.19254536]),
 5: array([-0.16396179, -0.08598625,  0.08855003,  0.06022842, -0.23702222,
        -0.122855  ,  0.02845249,  0.13759996, -0.05213575,  0.0250103 ]),
 6: array([-0.07632329, -0.09951056,  0.0239668 , -0.10192014,  0.04827593,
         0.2405843

In [4]:
# sample data sequences
sequence1 = [1, 13, 24, 12, 55, 1, 2, 3]
sequence2 = [2, 24, 15, 23, 3, 2, 1, 5]

In [5]:
# sample data point to hold our data
dat_point1 = np.zeros((8, 10))

In [6]:
# empty zeroes
dat_point1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
# fill each row with the weight for each corresponding word
for idx, val in enumerate(sequence1):
    dat_point1[idx] = embedding[val]

In [8]:
# this is the result that we get
dat_point1

array([[-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
        -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561],
       [-0.00194247, -0.06642845,  0.05810266, -0.00980326,  0.04479686,
        -0.08234598, -0.18053547, -0.05980147,  0.02925654,  0.14446727],
       [ 0.01743174,  0.03497554, -0.12777877,  0.09193585,  0.00146329,
         0.12833709,  0.13186136,  0.00732338,  0.14098355,  0.13262393],
       [-0.04711495,  0.005287  ,  0.06979388,  0.09878794,  0.04424998,
        -0.13985641,  0.17345973, -0.03961631, -0.12114504, -0.09049715],
       [-0.0598296 ,  0.08393214, -0.0577441 , -0.09504301,  0.02134259,
        -0.14081151,  0.02953415,  0.04044349,  0.01367545, -0.16315875],
       [-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
        -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561],
       [-0.11173917, -0.03611451,  0.09825518, -0.23787552,  0.07083221,
         0.01708899, -0.01817694, -0.0409453 

In [9]:
# notice how the word indices match the embedding weights
embedding[1]

array([-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
       -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561])

In [10]:
# function to 
def create_word_matrix(sequence, embedding, embedding_dim=10):
    data_point = np.zeros((len(sequence), embedding_dim))
    for idx, val in enumerate(sequence):
        data_point[idx] = embedding[val]
        
    return data_point

In [11]:
create_word_matrix(sequence1, embedding, 10)

array([[-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
        -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561],
       [-0.00194247, -0.06642845,  0.05810266, -0.00980326,  0.04479686,
        -0.08234598, -0.18053547, -0.05980147,  0.02925654,  0.14446727],
       [ 0.01743174,  0.03497554, -0.12777877,  0.09193585,  0.00146329,
         0.12833709,  0.13186136,  0.00732338,  0.14098355,  0.13262393],
       [-0.04711495,  0.005287  ,  0.06979388,  0.09878794,  0.04424998,
        -0.13985641,  0.17345973, -0.03961631, -0.12114504, -0.09049715],
       [-0.0598296 ,  0.08393214, -0.0577441 , -0.09504301,  0.02134259,
        -0.14081151,  0.02953415,  0.04044349,  0.01367545, -0.16315875],
       [-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
        -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561],
       [-0.11173917, -0.03611451,  0.09825518, -0.23787552,  0.07083221,
         0.01708899, -0.01817694, -0.0409453 

In [12]:
# wrap up our sequences in a list
sequences = [sequence1, sequence2]

In [13]:
# final matrix to hold our embedding data
word_data = np.zeros((2, 8, 10))

In [21]:
# fill in each row of the dataset with the encoded embedding data
for idx, row in enumerate(word_data):
    word_data[idx] = create_word_matrix(sequences[idx], embedding)

In [15]:
# this is what a single data point would look like
word_data[0]

array([[-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
        -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561],
       [-0.00194247, -0.06642845,  0.05810266, -0.00980326,  0.04479686,
        -0.08234598, -0.18053547, -0.05980147,  0.02925654,  0.14446727],
       [ 0.01743174,  0.03497554, -0.12777877,  0.09193585,  0.00146329,
         0.12833709,  0.13186136,  0.00732338,  0.14098355,  0.13262393],
       [-0.04711495,  0.005287  ,  0.06979388,  0.09878794,  0.04424998,
        -0.13985641,  0.17345973, -0.03961631, -0.12114504, -0.09049715],
       [-0.0598296 ,  0.08393214, -0.0577441 , -0.09504301,  0.02134259,
        -0.14081151,  0.02953415,  0.04044349,  0.01367545, -0.16315875],
       [-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
        -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561],
       [-0.11173917, -0.03611451,  0.09825518, -0.23787552,  0.07083221,
         0.01708899, -0.01817694, -0.0409453 

In [16]:
dat_point1[0]

array([-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
       -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561])

In [17]:
sequence1

[1, 13, 24, 12, 55, 1, 2, 3]

In [18]:
embedding[1]

array([-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
       -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561])

In [19]:
embedding


{0: array([ 0.0201575 , -0.00849058, -0.00466075, -0.01103659,  0.05213042,
        -0.28017484, -0.03202388,  0.0736791 , -0.09002325, -0.18466544]),
 1: array([-0.07016403, -0.01804342,  0.05531063,  0.10044151, -0.07124661,
        -0.0479853 , -0.05806376, -0.05455929,  0.1981196 ,  0.00024561]),
 2: array([-0.11173917, -0.03611451,  0.09825518, -0.23787552,  0.07083221,
         0.01708899, -0.01817694, -0.0409453 , -0.12994312, -0.03496482]),
 3: array([ 0.1608604 ,  0.01325084, -0.09057018, -0.19575602, -0.01248113,
        -0.06494003, -0.12170885, -0.0440194 ,  0.00523634,  0.02661695]),
 4: array([-0.10865877,  0.01773715, -0.02189519,  0.13157712,  0.06519128,
        -0.15469799,  0.14717475, -0.00379139, -0.08324313, -0.19254536]),
 5: array([-0.16396179, -0.08598625,  0.08855003,  0.06022842, -0.23702222,
        -0.122855  ,  0.02845249,  0.13759996, -0.05213575,  0.0250103 ]),
 6: array([-0.07632329, -0.09951056,  0.0239668 , -0.10192014,  0.04827593,
         0.2405843

In [22]:
word_data.shape

(2, 8, 10)